# Generated by Django 3.1 on 2021-02-25 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, help_text='Phone', max_length=50, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
